#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────



# A stage that MINTS A CREDENTIAL belongs in STATE_PATHS in provision-droplet.sh
# as well, or `dots droplet restore` rebuilds a host still missing it and you
# find out by being asked for it again. The drift only runs this way — a stale
# entry there is harmless, a missing one silently costs a stage. Stages that
# merely do work on the host (the scoped restore, pairing) are not credentials.
TOTAL_STAGES=10

# Non-secret bookkeeping only: the Tailscale auth key is single-use, so it is
# asked for and used, never written. Not guarded with `:-` on ENV_FILE — the
# library already defaulted it to `.env`, so a guarded assignment would keep
# that and drop a stray .env into this repo on the first write_env.
ENV_FILE="${DROPLET_WIZARD_ENV:-$HOME/.cache/droplet-wizard.env}"
mkdir -p "$(dirname "$ENV_FILE")"

DROPLET_NAME="${DROPLET_NAME:-t3code-host}"
REMOTE_USER="${REMOTE_USER:-jerome}"
# Same default and same override as provision-droplet.sh, which is what actually
# creates it — hardcoding the pattern here made stage 10 unmarkable for anyone
# who set FIREWALL_NAME.
FIREWALL_NAME="${FIREWALL_NAME:-$DROPLET_NAME-deny-all}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOPS_KEY="$HOME/.ssh/o27_socle_sops"
BACKUP_ARCHIVE="$HOME/Backups/projects-backup/projects-backup.tar.zst.age"

# provision-droplet.sh owns "where is the host" — it already has to answer that
# for setup/firewall/status, and its host_target falls back to the tailnet once
# stage 10 closes the public IP. Asking it here rather than re-deriving keeps the
# two scripts from disagreeing about the address, which is how a re-run of this
# wizard once died with no output at all at the first `$(rsh …)`.
# `|| true` because of `pipefail`: a missing or unauthenticated doctl would end
# the run before the message that says what to do about it.
TARGET=$(bash "$REPO_DIR/tools/provision-droplet.sh" target 2>/dev/null || true)
if [[ -z "$TARGET" ]]; then
  printf '%s cannot reach %s — run tools/provision-droplet.sh create first%s\n' \
    "$RED" "$DROPLET_NAME" "$RESET" >&2
  printf '%s (if that droplet does exist, check `doctl auth init`)%s\n' "$DIM" "$RESET" >&2
  exit 1
fi

# One SSH connection, reused by all ~29 of this run's commands. Without it each
# rsh/rsht/scp pays a full handshake and auth (~300ms); the first probe becomes
# the master and the rest are channel opens on it.
SSH_MUX=(-o ControlMaster=auto -o ControlPath="$HOME/.ssh/cm-droplet-%r@%h:%p"
         -o ControlPersist=300 -o StrictHostKeyChecking=accept-new)
# RPATH is prepended here rather than threaded through every call site: a stage
# that forgets it gets "command not found", which reads as a broken host. It is
# harmless on the probes, since exporting a PATH cannot change their answer.
RPATH='export PATH="$HOME/.local/bin:$HOME/.local/share/fnm/aliases/default/bin:$PATH";'
rsh()  { ssh "${SSH_MUX[@]}" "$TARGET" "$RPATH $*"; }
rsht() { ssh -t "${SSH_MUX[@]}" "$TARGET" "$RPATH $*"; }
rscp() { scp -q "${SSH_MUX[@]}" "$@"; }

# Resumability, which re-runnability alone is not.
#
# Re-running this wizard was always safe, but every stage asked its question
# again — and for Tailscale that is worse than pointless, since the auth key is
# single-use: you burn a fresh one to redo work already done. Each stage now
# states the condition that means it is finished, and skips itself when the host
# already satisfies it. The tests run ON the host, because the host is the only
# honest record of what happened; a local state file would drift the moment
# anything is done by hand.
#
# A skipped stage must cost neither a screen nor a keypress.
#
# The first version announced each one through the library's stage(), which
# clears the terminal — so the "already done" line needed a pause to be readable
# at all. On a re-run where eight of ten stages are done that is eight clears and
# eight Enters to read nothing, which is worse than the re-asking it replaced.
#
# Skipped stages now print one compact line each, with no clear and no pause, so
# they stack into a short list above the first stage that actually has work —
# the only one that needs the full frame. _STAGE_INDEX is the library's counter,
# advanced by hand here precisely because stage(), which normally does it, is
# the call being skipped.
#
# The tests are deliberately strict: a false negative only re-asks a question,
# while a false positive silently skips a step you needed.
remote_done() { [[ -z "${FORCE_ALL:-}" ]] && rsh "$1" >/dev/null 2>&1; }

# A decline is the one thing the host can never tell us.
#
# Everything else here is read from the host precisely because a local file
# drifts. But "I do not post screenshots on Forgejo PRs" is a decision, not a
# state, and re-asking it every run — reopening the same optional step forever —
# is the nagging this wizard's resumability exists to remove. So declines, and
# only declines, are recorded locally, next to the other non-secret bookkeeping.
# FORCE_ALL reopens them, same as everything else.
declined()       { [[ -z "${FORCE_ALL:-}" && -n "$(_existing "DECLINED_$1" || true)" ]]; }
record_decline() { write_env "DECLINED_$1" 1; }

# The compact one-liner a skipped stage prints instead of taking a screen and a
# keypress. Shared with stage 5, whose condition is two halves rather than one
# remote test.
skip_line() {
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '  %s✓%s %s%s/%s%s %s %s— %s%s\n' \
    "$GREEN" "$RESET" "$DIM" "$_STAGE_INDEX" "$TOTAL_STAGES" "$RESET" \
    "$1" "$DIM" "$2" "$RESET"
}

stage_or_skip() {
  local title="$1" test="${2:-}" msg="${3:-}"
  if [[ -n "$test" ]] && remote_done "$test"; then
    skip_line "$title" "$msg"
    return 1
  fi
  stage "$title"
  return 0
}

# The library's open_url runs the opener in the foreground, and xdg-open does
# not return until the browser it launched exits — so the wizard prints
# "opening", hands the terminal to a browser that will outlive the run, and
# never reaches the instructions below it. Looks like a wizard with nothing to
# say; it is a wizard that never got its turn back.
#
# Redefined here rather than edited above the marker, so the library stays
# stock: this definition is later, so it wins. `setsid -f` is what actually
# detaches — plain `setsid` does not fork when the caller is not a process
# group leader, which a script's subshell often is.
open_url() {
  local url="$1" opener="" c
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  for c in wslview explorer.exe xdg-open open; do
    if command -v "$c" >/dev/null 2>&1; then opener="$c"; break; fi
  done
  if [[ -z "$opener" ]]; then
    warn "couldn't open a browser — visit it manually: $url"
    return 0
  fi
  setsid -f "$opener" "$url" >/dev/null 2>&1 </dev/null \
    || { "$opener" "$url" >/dev/null 2>&1 </dev/null & disown; }
  return 0
}

banner "T3 Code host — the steps only you can do"

# Say where we are talking, before the first stage.
#
# Every "is this already done" test is a command run on the host, so a run that
# cannot reach the host sees all ten fail and re-asks everything — which looks
# exactly like a wizard that forgot, and sends you off to mint a Tailscale key
# you already have. One line naming the address, and a hard stop if it does not
# answer, turns that into an obvious diagnosis instead of a mystery.
if rsh true >/dev/null 2>&1; then
  note "Host: $TARGET"
else
  printf '%s  cannot reach %s — every check below would fail and every stage\n' "$RED" "$TARGET" >&2
  printf '  would re-ask. Fix the connection first: tools/provision-droplet.sh status%s\n' "$RESET" >&2
  exit 1
fi

# ── 1 ────────────────────────────────────────────────────────────────────────
if stage_or_skip "Tailscale — join the tailnet" \
     'tailscale status --peers=false' \
     "already on the tailnet"; then
  say "The host is reachable on its public IP right now. This is what replaces"
  say "that, and it has to work before the firewall closes the public IP."
  open_url "https://login.tailscale.com/admin/settings/keys"
  step "Click 'Generate auth key'."
  step "Leave it single-use; give it a short expiry. No tags needed."
  step "Copy the key (starts tskey-auth-)."
  ask_secret TS_AUTHKEY "Paste the auth key:"
  if [[ -n "${TS_AUTHKEY:-}" ]]; then
    # Through a file, not the command line: an --authkey argument is visible in
    # the host's process table for as long as the command runs.
    printf '%s' "$TS_AUTHKEY" | \
      rsh "umask 077 && cat > /tmp/ts.key \
           && sudo tailscale up --auth-key=file:/tmp/ts.key --hostname=$DROPLET_NAME; \
           rm -f /tmp/ts.key" \
      && printf '  %s✓%s host joined the tailnet\n' "$GREEN" "$RESET"
  else
    warn "no key given — skipping"; SKIPPED+=("tailscale up on the host")
  fi
fi
# Read unconditionally: stage 10 refuses to close the public IP without it, so
# it must be known even on a run where stage 1 was skipped.
# One payload, three facts: `tailscale status --json` already carries the state,
# the address and the MagicDNS name, so asking for them separately was three
# round trips for one answer.
TS_JSON=$(rsh 'tailscale status --json' 2>/dev/null || true)
TS_IP=""; TS_NAME=""
if [[ -n "$TS_JSON" ]]; then
  TS_IP=$(jq -r '.Self.TailscaleIPs[0] // empty' <<<"$TS_JSON" 2>/dev/null || true)
  TS_NAME=$(jq -r '.Self.DNSName // empty' <<<"$TS_JSON" 2>/dev/null | sed 's/\.$//' || true)
fi
[[ -n "$TS_IP" ]]   && write_env DROPLET_TAILNET_IP "$TS_IP"
[[ -n "$TS_NAME" ]] && write_env DROPLET_MAGICDNS "$TS_NAME"

# ── 2 ────────────────────────────────────────────────────────────────────────
if stage_or_skip "GitHub — authorize the host's own key" \
     'ssh -o BatchMode=yes -T git@github.com 2>&1 | grep -q "successfully authenticated"' \
     "GitHub accepts the host key"; then
# `|| true`: under `pipefail` an unreachable host makes this assignment fail, and
# `set -e` then ends the wizard mid-stage with nothing on screen.
HOST_KEY=$(rsh 'cat ~/.ssh/id_ed25519.pub' 2>/dev/null | tr -d '\r' || true)
[[ -n "$HOST_KEY" ]] || warn "Could not read the host's public key — is the host reachable?"
  say "The host generated its own keypair. Your ~/.ssh never left this machine,"
  say "so destroying the host costs a couple of revocations and nothing else."
  printf '\n  %s%s%s\n\n' "$BOLD" "$HOST_KEY" "$RESET"
  open_url "https://github.com/settings/ssh/new"
  step "Title: t3code-host"
  step "Key type: Authentication Key"
  step "Paste the key above, then 'Add SSH key'."
  pause "Added? Press Enter"
  if rsh 'ssh -o BatchMode=yes -T git@github.com 2>&1 | grep -q "successfully authenticated"'; then
    printf '  %s✓%s GitHub accepts the host key\n' "$GREEN" "$RESET"
  else
    warn "GitHub did not accept it yet"; SKIPPED+=("register the host key on GitHub")
  fi
fi

# ── 3 ────────────────────────────────────────────────────────────────────────
if stage_or_skip "Forgejo — authorize the same key for o27" \
     'ssh -o BatchMode=yes -T forgejo@git.o27.io 2>&1 | grep -qi "successfully authenticated"' \
     "Forgejo accepts the host key"; then
  say "socle and feedback live on your own forge; cppb is on GitHub."
  printf '\n  %s%s%s\n\n' "$BOLD" "$HOST_KEY" "$RESET"
  # git.o27.io is the forge's current name. git.postula.io and git.postulex.be
  # are the same host under older names — they still answer, which is exactly
  # why they are easy to keep depending on by accident.
  open_url "https://git.o27.io/user/settings/keys"
  step "'Add Key' → paste the key above → Title: t3code-host."
  pause "Added? Press Enter"
  if rsh 'ssh -o BatchMode=yes -T forgejo@git.o27.io 2>&1 | grep -qi "successfully authenticated"'; then
    printf '  %s✓%s Forgejo accepts the host key\n' "$GREEN" "$RESET"
  else
    warn "Forgejo did not accept it yet"; SKIPPED+=("register the host key on Forgejo")
  fi
fi

# ── 4 ────────────────────────────────────────────────────────────────────────
if stage_or_skip "sops — convey the o27 decryption key" \
     '[ -s ~/.ssh/o27_socle_sops ]' \
     "the sops key is in place"; then
  say "socle's .env.enc is encrypted to SSH recipients, and its MCP servers shell"
  say "out to sops at startup. Without this key the host decrypts nothing: no dev"
  say "server and no e2e run for o27."
  warn "This is a company decryption key leaving your desktop. It is the one"
  warn "secret this design deliberately moves, and it was decided knowingly."
  if [[ ! -f "$SOPS_KEY" ]]; then
    warn "$SOPS_KEY not found — skipping"; SKIPPED+=("copy the sops key to the host")
  elif confirm "Copy $SOPS_KEY to the host?"; then
    rscp "$SOPS_KEY" "$SOPS_KEY.pub" "$TARGET:.ssh/" \
      && rsh 'chmod 600 ~/.ssh/o27_socle_sops' \
      && printf '  %s✓%s sops key in place\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("copy the sops key to the host (o27 dev servers will not start)")
  fi
fi

# ── 5 ────────────────────────────────────────────────────────────────────────
gh_settled()   { remote_done "gh auth status" || declined GH_TOKEN; }
tea_settled()  { remote_done "tea logins list 2>/dev/null | grep -q t3code-host" || declined FORGEJO_TOKEN; }
if gh_settled && tea_settled; then
  skip_line "Forge tokens — how screenshots reach a PR" "both settled (done or declined)"
else
  stage "Forge tokens — how screenshots reach a PR"
say "Posting a review screenshot needs an API token, not just an SSH key. Both"
say "flows below mint a token that belongs to this host, so revoking it later"
say "does not touch your desktop."
say ""
# Two independent halves, each with its own check: having done one is no reason
# to be asked about the other again.
if remote_done "gh auth status"; then
  note "gh is already authenticated — nothing to do for GitHub."
elif declined GH_TOKEN; then
  note "gh login declined previously — FORCE_ALL=1 reopens it."
elif confirm "Run 'gh auth login' on the host? (choose SSH, then the browser flow)"; then
  rsht "gh auth login" || SKIPPED+=("gh auth login on the host")
else
  record_decline GH_TOKEN
  SKIPPED+=("gh auth login on the host")
fi
say ""
if remote_done "tea logins list 2>/dev/null | grep -q t3code-host"; then
  note "tea already has a t3code-host login."
elif declined FORGEJO_TOKEN; then
  note "Forgejo token declined previously — FORCE_ALL=1 reopens it."
# The confirm comes BEFORE open_url, which is the whole point: asked the other
# way round, declining still left you with a Forgejo tab you never asked for,
# every single run. Nothing optional should open a browser before you have said
# yes to it.
elif confirm "Set up the Forgejo token now? (needed only to post screenshots on a PR)"; then
  open_url "https://git.o27.io/user/settings/applications"
  step "Generate a token named t3code-host."
  # `repository` alone is not enough: tea identifies the account before it can
  # store a login, so it needs read:user too, and posting a screenshot on a PR
  # is an issue comment, not a repository write.
  step "Scopes: read:user, write:repository, write:issue."
  step "Copy it — Forgejo shows it once."
  ask_secret FORGEJO_TOKEN "Paste the token (Enter to abandon this stage):"
  if [[ -n "${FORGEJO_TOKEN:-}" ]]; then
    # `--token` rather than the prompt: `tea logins add` with some flags but no
    # --token has its own idea of what to still ask for, and a half-filled
    # interactive form over ssh -t is how this stage gets abandoned.
    #
    # But the value travels on stdin, not inside the command string — same rule
    # as the Tailscale key above. Interpolated, it sat in the desktop's `ssh`
    # argv and the host's `bash -c` argv for the length of the call, and a token
    # containing a quote broke out of the quoting outright.
    printf '%s\n' "$FORGEJO_TOKEN" \
      | rsh "read -r _tok && tea logins add --name t3code-host --url https://git.o27.io --token \"\$_tok\"" \
      || true
    # Verified by asking what actually landed, not by trusting the exit status.
    # Three valid tokens in a row were entered here and nothing was ever stored,
    # and the stage reported no failure worth noticing — so the check now is the
    # same one the skip test uses, which is the only claim that means anything.
    if rsh "tea logins list 2>/dev/null | grep -q t3code-host"; then
      printf '  %s✓%s Forgejo login stored\n' "$GREEN" "$RESET"
    else
      warn "tea did not store the login — the errors above are the reason."
      warn "Most often the token is missing the read:user scope."
      SKIPPED+=("tea login on the host")
    fi
  else
    SKIPPED+=("tea login on the host (screenshots cannot reach a Forgejo PR)")
  fi
else
  record_decline FORGEJO_TOKEN
  SKIPPED+=("tea login on the host (screenshots cannot reach a Forgejo PR)")
fi
fi

# ── 6 ────────────────────────────────────────────────────────────────────────
if stage_or_skip "Repos and secrets — the scoped restore" \
     '[ -f ~/.cache/droplet-restore-done ]' \
     "a scoped restore already completed"; then
# A marker written only after a restore that exited cleanly — NOT "does
# ~/Projects/labs exist". The first clone creates that directory, so a restore
# that died on its very first repo (which is how the https-vs-ssh bug above
# surfaced) satisfied the directory test and would have been skipped as done:
# the false positive this design exists to avoid.
  say "Clones the 11 repos of labs + o27 and drops their gitignored .env files"
  say "back in. mbrella is excluded; --no-home keeps your keyring off the host."
  note "Repos only, no worktrees — recreate those with 'wt' when you need them."
  say ""
  # The archive travels by scp rather than being pulled from the private backup
  # repo: that path wants an authenticated gh on the host *before* the restore,
  # and the desktop already holds the file. The restore scripts travel too, from
  # THIS checkout — the scoped-restore flags may not be pushed yet, and a clone
  # of the published repo would reject --only with "Unknown option".
  if [[ ! -f "$BACKUP_ARCHIVE" ]]; then
    warn "No archive at $BACKUP_ARCHIVE — run 'dots backup create' first"
    SKIPPED+=("restore repos and secrets on the host")
  elif confirm "Send the backup archive and restore? (asks for its age passphrase)"; then
    rsh 'mkdir -p ~/dots-restore/tools ~/dots-restore/install/lib'
    rscp "$REPO_DIR/tools/backup-projects.sh"  "$TARGET:dots-restore/tools/"
    rscp "$REPO_DIR/install/lib/common.sh"     "$TARGET:dots-restore/install/lib/"
    rscp "$BACKUP_ARCHIVE"                     "$TARGET:projects-backup.tar.zst.age"
    if rsht "bash ~/dots-restore/tools/backup-projects.sh restore \
             ~/projects-backup.tar.zst.age --only labs,o27 --no-home"; then
      rsh 'mkdir -p ~/.cache && touch ~/.cache/droplet-restore-done'
      note "If any clone printed 'Failed to clone' above, fix it and re-run"
      note "this stage with FORCE_ALL=1 — the restore skips repos already there."
    else
      SKIPPED+=("the scoped restore (re-run this stage)")
    fi
  else
    SKIPPED+=("restore repos and secrets on the host")
  fi
fi

# ── 7 ────────────────────────────────────────────────────────────────────────
if stage_or_skip "Claude Code — sign in" \
     '[ -s ~/.claude/.credentials.json ] || grep -q oauthAccount ~/.claude.json 2>/dev/null' \
     "Claude Code is signed in"; then
  say "A browser flow: the CLI prints a URL, you approve it, you paste the code"
  say "back. This is a second session of your subscription, running remotely."
  if confirm "Start 'claude' login on the host?"; then
    rsht "claude" || SKIPPED+=("claude login on the host")
  else
    SKIPPED+=("claude login on the host")
  fi
fi

# ── 8 ────────────────────────────────────────────────────────────────────────
if stage_or_skip "Codex — sign in" \
     '[ -s ~/.codex/auth.json ]' \
     "Codex is signed in"; then
  say "Codex prints a one-time code; you enter it on the page below."
  # --device-auth, not a bare `codex login`. The plain form starts a callback
  # server on the HOST's localhost:1455 and hands you a URL whose redirect_uri
  # is that same localhost — so opening it on the desktop redirects to a port
  # where nothing is listening, and the login silently never completes. Codex
  # says so itself in the last line of its own output. The flag is absent from
  # `codex login --help` in 0.147.0 but is accepted; verified on the host.
  open_url "https://auth.openai.com/codex/device"
  step "Sign in, then type the code the terminal shows below."
  if confirm "Start 'codex login --device-auth' on the host?"; then
    rsht "codex login --device-auth" || SKIPPED+=("codex login on the host")
  else
    SKIPPED+=("codex login on the host")
  fi
  note "Linear's MCP is OAuth too, but it authenticates on first use inside a"
  note "session in socle — nothing to do here."
fi

# ── 9 ────────────────────────────────────────────────────────────────────────
stage "Pair your desktop and your phone"
note "The service itself is already installed and running — provisioning does"
note "that, since it needs nobody. This stage is only the pairing."
say "'t3 pair --tailscale' publishes the server over Tailscale Serve HTTPS and"
say "prints a pairing URL plus a QR code."
step "Scan the QR with the T3 Code app on your phone."
step "Desktop app: Settings → Connections → Add environment → paste the URL."
warn "A pairing code is SINGLE-USE. One run pairs one device — this stage loops"
warn "so each device gets its own, rather than handing the second one a code the"
warn "first already burned (\"The environment credential is invalid\")."
# Measured, not asserted. This used to be a hardcoded warning that MagicDNS was
# "probably broken" here, copied from a tailnet health check — which stayed on
# screen long after `tailscale set --accept-dns=true` fixed it, telling you to
# work around a problem you no longer had. The pairing URL is a MagicDNS name,
# so whether it resolves ON THIS DESKTOP is the only thing worth saying.
if [[ -n "$TS_NAME" ]] && getent ahostsv4 "$TS_NAME" >/dev/null 2>&1; then
  note "MagicDNS resolves here: $TS_NAME"
else
  warn "$TS_NAME does not resolve on this desktop, so the pairing URL will not"
  warn "open here. Your phone has its own resolver and is unaffected."
  warn "Fix with 'tailscale set --accept-dns=true', or use ${TS_IP:-the 100.x address}."
fi
# No skip test: a pairing token is per-device and short-lived, so "already
# paired" is not a state the host can answer for. Re-running mints a new token,
# which costs nothing and is often exactly what you came back for.
note "Adding a device later is its own command, not a re-run of this wizard:"
note "  tools/provision-droplet.sh pair"
if confirm "Mint a pairing code now?"; then
  while :; do
    rsht "t3 pair --tailscale"
    pause "Paired that device? Press Enter"
    confirm "Pair another device with a fresh code?" || break
  done
else
  SKIPPED+=("t3 pair --tailscale (run 'provision-droplet.sh pair' when you want it)")
fi

# ── 10 ───────────────────────────────────────────────────────────────────────
stage "Close the public IP"
# The one probe that is local, not remote — DO owns this fact, not the host.
# It still honours FORCE_ALL, and it keeps a pause of its own: this is the last
# stage, and `finish` opens by clearing the screen, so without one the closing
# address is wiped before it can be read.
if [[ -z "${FORCE_ALL:-}" ]] \
   && doctl compute firewall list --format Name --no-header 2>/dev/null | grep -qx "$FIREWALL_NAME"; then
  note "The deny-all firewall is already in place."
  note "Reach the host at ssh $REMOTE_USER@${TS_IP:-<tailnet ip>}"
  pause "Press Enter to finish"
else
  say "Last, and the one step with a way to lock yourself out — which is why it"
  say "runs after Tailscale, not before. Recovery is the DO web console: it goes"
  say "through the hypervisor and does not care about the firewall."
  if [[ -z "${TS_IP:-}" ]]; then
    warn "The host is not on the tailnet — refusing to close its only door."
    SKIPPED+=("apply the deny-all firewall (host was not on the tailnet)")
  elif confirm "Apply the deny-all firewall now?"; then
    bash "$REPO_DIR/tools/provision-droplet.sh" firewall
    say ""
    say "From now on, reach the host over the tailnet:"
    note "  ssh $REMOTE_USER@${TS_IP}"
  else
    SKIPPED+=("apply the deny-all firewall")
  fi
fi

finish
